name: test on amazonlinux

# https://github.community/t/trigger-workflow-only-on-pull-request-merge/17359
on:
  # manual trigger
  workflow_dispatch:
  # most pushes to master are the result of a pull request, so this is effectively
  # "on pull_request merge to master"
  push:
    branches:
      - lambda
      - gh-actions-2

jobs:
  test-image-builder:
    strategy:
      matrix:
        os-version: [
          'amazonlinux:2+node:10', 'amazonlinux:2+node:12'
        ]
    runs-on: ubuntu-latest
    # (os-version) is appended, so "test" appears "test (amazonlinux:2+node:10)"
    name: test
    steps:
    # To use a repo-specific action you must check out the repository
    - name: Checkout to root dir
      uses: actions/checkout@v2
    # jump through a little hoop to get the branch by itself
    - name: get branch
      run: echo "gh_branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
    - name: Create specific alpine/node image
      id: generic
      uses: ./.github/actions/generic
      with:
        # specify testing the branch that this was invoked for
        branch-to-test: ${{env.gh_branch}}
        ao-token-prod: ${{secrets.AO_TOKEN_PROD}}
        node-image: ${{matrix.os-version}}
    # Use the output from the `generic` step
    - name: show info, context, and debugging information
      run: |
        echo "all args 1 ${{steps.generic.outputs.all-args}}"
        echo "all args 2 ${{steps.generic.outputs.all-args-2}}"
        echo "os ${{steps.generic.outputs.os-details}}"
        echo "branch ${{steps.generic.outputs.branch-to-test}}"
    - name: test results
      run: |
        echo "npm install --production --unsafe-perm: ${{steps.generic.outputs.install-prod}}"
        echo "npm install --unsafe-perm: ${{steps.generic.outputs.install-dev}}"
        echo "tests passed: ${{steps.generic.outputs.tests-passed-count}}"
        echo "tests failed: ${{steps.generic.outputs.tests-failed-count}} - ${{steps.generic.outputs.tests-failed}}"
