name: on-pull-request node-ubuntu matrix

on: [pull_request]

jobs:
  test:
    runs-on: ${{matrix.operating-system}}

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        operating-system: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04]

    steps:
      - uses: actions/checkout@v2
      - name: on node v${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - name: Environment Information
        run: npx envinfo
      - run: npm install -g mocha
      - name: verify install works
        run: npm install
      - name: get core tests working
        run: npm test
        env:
          APPOPTICS_COLLECTOR: collector.appoptics.com
          APPOPTICS_REPORTER: ssl
          AO_TOKEN_PROD: ${{secrets.AO_TOKEN_PROD}}
