name: on-push node-matrix on ubuntu

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v2
      - name: on node v${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - name: Environment Information
        run: npx envinfo
      - run: npm install -g mocha
      - name: verify install works
        run: npm install
      - name: get core tests working
        run: npm test
        env:
          APPOPTICS_COLLECTOR: collector.appoptics.com
          APPOPTICS_REPORTER: ssl
          AO_TOKEN_PROD: ${{ secrets.AO_TOKEN_PROD }}
